package app.domain.models;

public enum OperationType {
    ACCOUNT_OPENING,
    TRANSFER_CREATION,
    TRANSFER_APPROVAL,
    TRANSFER_REJECTION,
    TRANSFER_EXECUTION,
    TRANSFER_EXPIRATION,
    LOAN_REQUEST,
    LOAN_APPROVAL,
    LOAN_REJECTION,
    LOAN_DISBURSEMENT,
    USER_REGISTRATION,
    USER_UPDATE
}
